---
title: "SBUX Stock Predictor"
author: "Cameron Williams"
date: "3/7/2022"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r}
#data cleanup
install.packages("dplyr",repos = "http://cran.us.r-project.org")
install.packages("tidyr",repos = "http://cran.us.r-project.org")
install.packages("magrittr",repos = "http://cran.us.r-project.org")
install.packages("stringr",repos = "http://cran.us.r-project.org")
install.packages("lubridate",repos = "http://cran.us.r-project.org")
install.packages("data.table",repos = "http://cran.us.r-project.org")
library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
library(lubridate)
library(data.table)
#api and Json
install.packages("httr",repos = "http://cran.us.r-project.org")
install.packages("jsonlite",repos = "http://cran.us.r-project.org")
install.packages("config",repos = "http://cran.us.r-project.org")
library(httr)
library(jsonlite)
library(config)
#webscraping
install.packages("rvest",repos = "http://cran.us.r-project.org")
library(rvest)
#visualization
install.packages("plotly",repos = "http://cran.us.r-project.org")
install.packages("ggplot2",repos = "http://cran.us.r-project.org")
install.packages("DT",repos = "http://cran.us.r-project.org")
library(plotly)
library(ggplot2)
library(DT)
#data
install.packages("bea.R",repos = "http://cran.us.r-project.org")
install.packages("devtools",repos = "http://cran.us.r-project.org")
install.packages("gtrendsR",repos = "http://cran.us.r-project.org")
library(bea.R)
library(gtrendsR)
#text analysis
install.packages("tidytext",repos = "http://cran.us.r-project.org")
install.packages("wordcloud",repos = "http://cran.us.r-project.org")
install.packages("RColorBrewer",repos = "http://cran.us.r-project.org")
library(tidytext)
library(wordcloud)
library(RColorBrewer)
#forecasting
install.packages("quantmod",repos = "http://cran.us.r-project.org")
install.packages("forecast",repos = "http://cran.us.r-project.org")
install.packages("tseries",repos = "http://cran.us.r-project.org")
install.packages("prophet",repos = "http://cran.us.r-project.org")
install.packages("xts",repos = "http://cran.us.r-project.org")
install.packages("timeseries",repos = "http://cran.us.r-project.org")
library(timeSeries)
library(quantmod)
library(forecast)
library(tseries)
library(prophet)
library(xts)


```





```{r setup, include=FALSE}
getSymbols('SBUX', from ='1993-1-01', to='2022-2-27')
class(SBUX)
#Bring in closed prices for the day
STNE_Close_Prices = SBUX[,4] #this will give you closing prices
plot(STNE_Close_Prices)
class(STNE_Close_Prices)
```

```{r}
par(mfrow=c(1,1))
acf(STNE_Close_Prices, main = 'ACF For Differenced Series')
pacf(STNE_Close_Prices, main = 'PCF For Differenced Series')
```

```{r, echo=FALSE}
# p value is higher than 0.05 not statistically significant
print(adf.test(STNE_Close_Prices))
auto.arima(STNE_Close_Prices, seasonal = FALSE)
```

```{r}
fitA = auto.arima(STNE_Close_Prices, seasonal = FALSE)
tsdisplay(residuals(fitA), lag.max = 40, main='(2.1.0) Model Residuals')
auto.arima(STNE_Close_Prices, seasonal=FALSE)

fitB=arima(STNE_Close_Prices, order=c(2, 1, 2))
tsdisplay(residuals(fitB), lag.max = 40, main = '(2, 1, 2) Model Residuals')

fitC = arima(STNE_Close_Prices, order = c(2, 2, 0))
tsdisplay(residuals(fitB), lag.max = 40, main = '(2.2.0) Model Residuals')

fitD = arima(STNE_Close_Prices, order = c(1, 1, 1))
tsdisplay(residuals(fitB), lag.max = 40, main = '(1,1,1) Model Residuals')
```

```{r}
par(mfrow = c(2,2))

term <- 1825 #the number of days you are looking to predict in the future. 

fcast1 <- forecast(fitA, h=term)
plot(fcast1, main = "Fit A")
fcast2 <- forecast(fitB, h=term)
plot(fcast2, main = "Fit B")
fcast3 <- forecast(fitC, h=term)
plot(fcast3, main = "Fit C")
fcast4 <- forecast(fitD, h=term)
plot(fcast4, main = "Fit D")

#100 - MAPE = accuracy %
accuracy(fcast1)
accuracy(fcast2)
accuracy(fcast3)
accuracy(fcast4)
```